DIR = ./build
TARGET  = $(DIR)/BARULANDIA.PS3.linux
INCLUDE = ./include
SRCS    = $(wildcard ./source/*.cpp)
FLAGS   = -o$(TARGET) -Wall -g -std=gnu++11 -lSDL -lSDL_image -lSDL_ttf -lstdc++ -lm

$(TARGET): $(DIR) $(SRCS)
	gcc $(SRCS) -I$(INCLUDE) $(FLAGS)

$(DIR):
	mkdir $(DIR)

clean:
	rm -f $(TARGET)
	rm -fr $(DIR)
