TARGET  = ./build/BARULANDIA.PS3.linux
INCLUDE = ./include
SRCS    = $(wildcard ./source/*.cpp)
FLAGS   = -o$(TARGET) -Wall -O3 `sdl2-config --cflags --libs` `libmikmod-config --cflags --libs` -lSDL2_image -lSDL2_ttf -lstdc++

$(TARGET): $(SRCS)
	gcc $(SRCS) -I$(INCLUDE) $(FLAGS)

clean:
	rm -f $(TARGET)
